services:
  mysql:
    container_name: prestashop_mysql
    image: mysql:latest
    # platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - '3306:3306'
  prestashop:
    container_name: prestashop_ps
    # image: prestashop/prestashop:latest
    image: prestashop/prestashop:1.8
    # platform: linux/amd64
    restart: always
    depends_on:
      - mysql
    ports:
      - '80:80'
    environment:
      DB_SERVER: prestashop_mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_FOLDER_ADMIN: admin
      PS_FOLDER_INSTALL: install
    networks:
      - prestashop_network
    volumes:
      - ./prestaDocker:/var/www/html
networks:
  prestashop_network:
volumes:
  prestaLocal:
  dbdata:
